                                                                processor 16f877
include <p16f877.inc>
REGB equ h'21'
REGA equ h'22'
COUNT1 equ h'35'
COUNT2 equ h'36'
cte1 equ .33; B
cte2 equ h'FF'  ; A
 	ORG 0
GOTO INICIO
 	ORG 5
INICIO:
	CLRF PORTA
	BSF STATUS,RP0
 	BCF STATUS,RP1
 	MOVLW H'00'
 	MOVWF TRISB
	MOVWF TRISC
	MOVWF TRISD
	MOVLW 06H
	MOVWF ADCON1
	MOVLW 3FH
	MOVWF TRISA
 	BCF STATUS,RP0
	MOVLW B'00000000'
	MOVWF PORTB
	MOVWF PORTC
	MOVWF PORTD
loop1:
	MOVLW h'00'		;
	SUBWF PORTA, W	; PORTA = 0 ?
	BTFSC STATUS, Z	;
	GOTO PARO	; VAMOS A PARO

	MOVLW h'01'		;
	SUBWF PORTA, W	; PORTA = 1 ? 
	BTFSC STATUS, Z	;
	GOTO H			; VAMOS A H

	MOVLW h'02'		;
	SUBWF PORTA, W	; PORTA = 2 ?
	BTFSC STATUS, Z	; 
	GOTO AH			; VAMOS A AH

	MOVLW h'03'		;
	SUBWF PORTA, W	;
	BTFSC STATUS, Z	;
	GOTO CINCO_H	;

	MOVLW h'04'	
	SUBWF PORTA, W
	BTFSC STATUS, Z
	GOTO DIEZ_AH

goto loop1	

PARO:
 	CLRF PORTB
	GOTO loop1
H:
	CLRF PORTB
	BSF PORTB, 7 ;
	BSF PORTB, 6 ;
	BCF PORTB, 5 ;
	BCF PORTB, 4 ;PASO 1
	CALL RETARDO
	BCF PORTB, 7 ;
	BSF PORTB, 6 ;
	BSF PORTB, 5 ;
	BCF PORTB, 4 ;PASO 2
	CALL RETARDO
	BCF PORTB, 7 ;
	BCF PORTB, 6 ;
	BSF PORTB, 5 ;
	BSF PORTB, 4 ;PASO 3
	CALL RETARDO
	BSF PORTB, 7 ;
	BCF PORTB, 6 ;
	BCF PORTB, 5 ;
	BSF PORTB, 4 ;PASO 4
	CALL RETARDO
	GOTO loop1
AH:
	CLRF PORTB
	BSF PORTB, 7 ;
	BCF PORTB, 6 ;
	BCF PORTB, 5 ;
	BSF PORTB, 4 ;PASO 4
	CALL RETARDO
	BCF PORTB, 7 ;
	BCF PORTB, 6 ;
	BSF PORTB, 5 ;
	BSF PORTB, 4 ;PASO 3
	CALL RETARDO
	BCF PORTB, 7 ;
	BSF PORTB, 6 ;
	BSF PORTB, 5 ;
	BCF PORTB, 4 ;PASO 2
	CALL RETARDO	
	BSF PORTB, 7 ;
	BSF PORTB, 6 ;
	BCF PORTB, 5 ;
	BCF PORTB, 4 ;PASO 1
	CALL RETARDO
	GOTO loop1
CINCO_H:
		CLRF COUNT1
		CLRF COUNT2
	loop_h_1:
		MOVLW H'0A'
		SUBWF COUNT1, W
		BTFSC STATUS, Z
		GOTO end_loop_h_1
	loop_h_2:
		;BSF PORTD, 5
		MOVLW H'FF'
		SUBWF COUNT2, W
		BTFSC STATUS, Z
		GOTO end_loop_h_2

		CLRF PORTB
		BSF PORTB, 7 ;
		BSF PORTB, 6 ;
		BCF PORTB, 5 ;
		BCF PORTB, 4 ;PASO 1
		CALL RETARDO
		BCF PORTB, 7 ;
		BSF PORTB, 6 ;
		BSF PORTB, 5 ;
		BCF PORTB, 4 ;PASO 2
		CALL RETARDO
		BCF PORTB, 7 ;
		BCF PORTB, 6 ;
		BSF PORTB, 5 ;
		BSF PORTB, 4 ;PASO 3
		CALL RETARDO
		BSF PORTB, 7 ;
		BCF PORTB, 6 ;
		BCF PORTB, 5 ;
		BSF PORTB, 4 ;PASO 4
		CALL RETARDO
		INCF COUNT2, 1
		GOTO loop_h_2
		
end_loop_h_1:
		
		MOVLW h'03'		;
		SUBWF PORTA, W	;
		BTFSC STATUS, Z	;
		GOTO end_loop_h_1
		GOTO loop1

end_loop_h_2:
		MOVFW COUNT2
		MOVWF PORTD
		INCF COUNT1, 1
		CLRF COUNT2
		GOTO loop_h_1
DIEZ_AH:
		CLRF COUNT1
		CLRF COUNT2
	loop_ah_1:
		MOVLW H'14'
		SUBWF COUNT1, W
		BTFSC STATUS, Z

		GOTO end_loop_ah_1
	loop_ah_2:
		MOVLW H'FF'
		SUBWF COUNT2, W
		BTFSC STATUS, Z
		GOTO end_loop_ah_2

		CLRF PORTB
		BSF PORTB, 7 ;
		BCF PORTB, 6 ;
		BCF PORTB, 5 ;
		BSF PORTB, 4 ;PASO 4
		CALL RETARDO
		BCF PORTB, 7 ;
		BCF PORTB, 6 ;
		BSF PORTB, 5 ;
		BSF PORTB, 4 ;PASO 3
		CALL RETARDO
		BCF PORTB, 7 ;
		BSF PORTB, 6 ;
		BSF PORTB, 5 ;
		BCF PORTB, 4 ;PASO 2
		CALL RETARDO	
		BSF PORTB, 7 ;
		BSF PORTB, 6 ;
		BCF PORTB, 5 ;
		BCF PORTB, 4 ;PASO 1
		CALL RETARDO
		INCF COUNT2, 1
		GOTO loop_ah_2
		
end_loop_ah_1:
		
		MOVLW h'04'		;
		SUBWF PORTA, W	;
		BTFSC STATUS, Z	;
		GOTO end_loop_ah_1
		GOTO loop1

end_loop_ah_2:
		MOVFW COUNT2
		MOVWF PORTD
		INCF COUNT1, 1
		CLRF COUNT2
		GOTO loop_ah_1
	
RETARDO:		; 
	MOVLW cte1	;
 	MOVWF REGB	;
LOOPB: 			;
	MOVLW cte2	;
	MOVWF REGA	;
LOOPA: 			;
	DECFSZ REGA	;
 	GOTO LOOPA	;
	DECFSZ REGB	;
	GOTO LOOPB	;
	RETURN		; CODIGO PARA EL RETARDO
	END