PROCESSOR 16f877
INCLUDE <p16f877.inc> 

MAX equ H'40'
	ORG 0
 	GOTO INICIO 
 	ORG 5
INICIO:
	MOVLW H'FF'
	MOVWF MAX 
	BCF STATUS,RP1
	BCF STATUS,RP0; pone el banco en 00
	MOVLW 0X1F
	MOVWF FSR
LOOP: 
	INCF FSR; Incrementa el apuntador FSR
	MOVF MAX,W
	SUBWF INDF,0; F - W
	BTFSS STATUS, C
	GOTO CHECK_Z
CONTINUE:
	BTFSS FSR,6 ;Mientras FSR no tenga el bit 6 encendido, haremos el loop
	GOTO LOOP
	GOTO $
CHECK_Z:
	BTFSC STATUS, Z
	GOTO CONTINUE
	MOVFW INDF
	MOVWF MAX
	GOTO CONTINUE
	END